# This is the configuration used to check the rubocop source code.

AllCops:
  NewCops: enable
  Exclude:
    - 'test/fixtures/*'

Style/StringLiterals:
  Enabled: true

Style/RedundantPercentQ:
  Enabled: true

# Disabled Checks
Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Lint/MissingCopEnableDirective:
  Exclude:
    - 'test/base_test.rb'

Naming/MethodParameterName:
  Exclude:
    - 'lib/virustotal_api/ip_report.rb'

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false
