# This is the configuration used to check the rubocop source code.

AllCops:
  Exclude:
    - 'test/fixtures/*'

Style/StringLiterals:
  Enabled: true

Style/UnneededPercentQ:
  Enabled: true

# Disabled Checks
Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Lint/MissingCopEnableDirective:
  Exclude:
    - 'test/base_test.rb'

Naming/UncommunicativeMethodParamName:
  Exclude:
    - 'lib/virustotal_api/ip_report.rb'
